/**
 * In house part class which is a subclass of Part.
 * @author Steven Barton
 */
public class InHouse extends Part {
    private int machineId;

    /**
     * In house part constructor generates a new in house part.
     * @param id Integer- ID number assigned to the part, this will be generated by the inventory.
     * @param name String- name of the part.
     * @param price Double- price of the part.
     * @param stock Integer- Number of the part on hand.
     * @param min Integer- Minimum number to keep on hand.
     * @param max Integer- Maximum number to keep on hand.
     * @param machineId Integer- The ID of the machine used to produce the part.
     */
    public InHouse(int id, String name, double price, int stock, int min, int max, int machineId) {
        super(id, name, price, stock, min, max);
        this.machineId = machineId;
    }

    /**
     * Assigns a machine ID to the in house part.
     * @param machineId Integer- The ID of the machine used to produce the part.
     */
    public void setMachineId(int machineId) {
        this.machineId = machineId;
    }

    /**
     * Returns the machine id for the in house part.
     * @return int value of the machine ID for this part.
     */
    public int getMachineId() {
        return this.machineId;
    }

 }
