/**
 * Outsourced part class which is a subclass of Part.
 * @author Steven Barton
 */
public class Outsourced extends Part {
    private String companyName;

    /**
     * Outsourced part constructor generates a new Outsourced object.
     * @param id Integer- ID number assigned to the part, this will be generated by the inventory.
     * @param name String- name of the part.
     * @param price Double- price of the part.
     * @param stock Integer- Number of the part on hand.
     * @param min Integer- Minimum number to keep on hand.
     * @param max Integer- Maximum number to keep on hand.
     * @param companyName String- The name of the company producing the part.
     */
    public Outsourced(int id, String name, double price, int stock, int min, int max, String companyName) {
        super(id, name, price, stock, min, max);
        this.companyName = companyName;
    }

    /**
     * Assigns a source company name to the outsourced part.
     * @param companyName String- The name of the company producing the part.
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * Returns the source company name of the outsourced part.
     * @return String value of the name of the supplier company.
     */
    public String getCompanyName() {
        return this.companyName;
    }
}
